import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
opacity = 0.99
decorations = "None"

[window.dimensions]
columns = 105
lines = 30

[window.padding]
x = 20
y = 20
